package com.experiencepvp.kits.utils;

import com.experiencepvp.kits.utils.kits.AnchorUtil;
import com.experiencepvp.kits.utils.kits.AntiStomperUtil;
import com.experiencepvp.kits.utils.kits.ArcherUtil;
import com.experiencepvp.kits.utils.kits.CatcherUtil;
import com.experiencepvp.kits.utils.kits.ElementalUtil;
import com.experiencepvp.kits.utils.kits.EndermanUtil;
import com.experiencepvp.kits.utils.kits.FeatherUtil;
import com.experiencepvp.kits.utils.kits.FishermanUtil;
import com.experiencepvp.kits.utils.kits.FlashUtil;
import com.experiencepvp.kits.utils.kits.GamblerUtil;
import com.experiencepvp.kits.utils.kits.GladiatorUtil;
import com.experiencepvp.kits.utils.kits.GodUtil;
import com.experiencepvp.kits.utils.kits.GrandpaUtil;
import com.experiencepvp.kits.utils.kits.GrapplerUtil;
import com.experiencepvp.kits.utils.kits.HulkUtil;
import com.experiencepvp.kits.utils.kits.JellyfishUtil;
import com.experiencepvp.kits.utils.kits.KangarooUtil;
import com.experiencepvp.kits.utils.kits.NinjaUtil;
import com.experiencepvp.kits.utils.kits.PhantomUtil;
import com.experiencepvp.kits.utils.kits.PoseidonUtil;
import com.experiencepvp.kits.utils.kits.PvPUtil;
import com.experiencepvp.kits.utils.kits.ReaperUtil;
import com.experiencepvp.kits.utils.kits.RogueUtil;
import com.experiencepvp.kits.utils.kits.SamuraiUtil;
import com.experiencepvp.kits.utils.kits.SnailUtil;
import com.experiencepvp.kits.utils.kits.SonicUtil;
import com.experiencepvp.kits.utils.kits.SpecialistUtil;
import com.experiencepvp.kits.utils.kits.StomperUtil;
import com.experiencepvp.kits.utils.kits.SwitcherUtil;
import com.experiencepvp.kits.utils.kits.TankUtil;
import com.experiencepvp.kits.utils.kits.ThorUtil;
import com.experiencepvp.kits.utils.kits.TurretUtil;
import com.experiencepvp.kits.utils.kits.TurtleUtil;
import com.experiencepvp.kits.utils.kits.ViperUtil;

public class Kits {
	public static PvPUtil pvp = new PvPUtil();
	public static ArcherUtil archer = new ArcherUtil();
	public static GamblerUtil gambler = new GamblerUtil();
	public static StomperUtil stomper = new StomperUtil();
	public static KangarooUtil kangaroo = new KangarooUtil();
	public static FishermanUtil fisherman = new FishermanUtil();
	public static ThorUtil thor = new ThorUtil();
	public static ViperUtil viper = new ViperUtil();
	public static PhantomUtil phantom = new PhantomUtil();
	public static SnailUtil snail = new SnailUtil();
	public static NinjaUtil ninja = new NinjaUtil();
	public static ReaperUtil reaper = new ReaperUtil();
	public static HulkUtil hulk = new HulkUtil();
	public static EndermanUtil enderman = new EndermanUtil();
	public static TurtleUtil turtle = new TurtleUtil();
	public static GladiatorUtil gladiator = new GladiatorUtil();
	public static SwitcherUtil switcher = new SwitcherUtil();
	public static SamuraiUtil samurai = new SamuraiUtil();
	public static GrapplerUtil grappler = new GrapplerUtil();
	public static JellyfishUtil jellyfish = new JellyfishUtil();
	public static SpecialistUtil specialist = new SpecialistUtil();
	public static GrandpaUtil grandpa = new GrandpaUtil();
	public static PoseidonUtil poseidon = new PoseidonUtil();
	public static AnchorUtil anchor = new AnchorUtil();
	public static RogueUtil rogue = new RogueUtil();
	public static FeatherUtil feather = new FeatherUtil();
	public static SonicUtil sonic = new SonicUtil();
	public static FlashUtil flash = new FlashUtil();
	public static TankUtil tank = new TankUtil();
	public static AntiStomperUtil antistomper = new AntiStomperUtil();
	public static ElementalUtil elemental = new ElementalUtil();
	public static TurretUtil turret = new TurretUtil();
	public static CatcherUtil catcher = new CatcherUtil();
	public static GodUtil god = new GodUtil();
}
